0	26	http://dev.mysql.com/doc/refman/5.7/en/logical-operators.html
1	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
2	29	http://dev.mysql.com/doc/refman/5.7/en/arithmetic-functions.html
3	3	http://dev.mysql.com/doc/refman/5.7/en/bit-functions.html
4	29	http://dev.mysql.com/doc/refman/5.7/en/arithmetic-functions.html
5	29	http://dev.mysql.com/doc/refman/5.7/en/arithmetic-functions.html
6	29	http://dev.mysql.com/doc/refman/5.7/en/arithmetic-functions.html
7	29	http://dev.mysql.com/doc/refman/5.7/en/arithmetic-functions.html
8	27	http://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html
9	27	http://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html
10	29	http://dev.mysql.com/doc/refman/5.7/en/arithmetic-functions.html
11	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
12	3	http://dev.mysql.com/doc/refman/5.7/en/bit-functions.html
13	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
14	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
15	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
16	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
17	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
18	3	http://dev.mysql.com/doc/refman/5.7/en/bit-functions.html
19	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
20	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
21	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
22	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
23	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
24	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
25	8	http://dev.mysql.com/doc/refman/5.7/en/alter-database.html
26	8	http://dev.mysql.com/doc/refman/5.7/en/alter-event.html
27	8	http://dev.mysql.com/doc/refman/5.7/en/alter-function.html
28	8	http://dev.mysql.com/doc/refman/5.7/en/alter-instance.html
29	8	http://dev.mysql.com/doc/refman/5.7/en/alter-logfile-group.html
30	8	http://dev.mysql.com/doc/refman/5.7/en/alter-procedure.html
31	8	http://dev.mysql.com/doc/refman/5.7/en/alter-server.html
32	8	http://dev.mysql.com/doc/refman/5.7/en/alter-table.html
33	8	http://dev.mysql.com/doc/refman/5.7/en/alter-tablespace.html
34	1	http://dev.mysql.com/doc/refman/5.7/en/alter-user.html
35	8	http://dev.mysql.com/doc/refman/5.7/en/alter-view.html
36	36	http://dev.mysql.com/doc/refman/5.7/en/analyze-table.html
37	26	http://dev.mysql.com/doc/refman/5.7/en/logical-operators.html
38	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
39	32	http://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html
40	40	http://dev.mysql.com/doc/refman/5.7/en/gis-format-conversion-functions.html
41	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
42	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
43	26	http://dev.mysql.com/doc/refman/5.7/en/assignment-operators.html
44	26	http://dev.mysql.com/doc/refman/5.7/en/assignment-operators.html
45	40	http://dev.mysql.com/doc/refman/5.7/en/gis-format-conversion-functions.html
46	27	http://dev.mysql.com/doc/refman/5.7/en/enterprise-encryption-functions.html
47	27	http://dev.mysql.com/doc/refman/5.7/en/enterprise-encryption-functions.html
48	27	http://dev.mysql.com/doc/refman/5.7/en/enterprise-encryption-functions.html
49	27	http://dev.mysql.com/doc/refman/5.7/en/enterprise-encryption-functions.html
50	27	http://dev.mysql.com/doc/refman/5.7/en/enterprise-encryption-functions.html
51	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
52	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
53	10	http://dev.mysql.com/doc/refman/5.7/en/example-auto-increment.html
54	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
55	5	http://dev.mysql.com/doc/refman/5.7/en/begin-end.html
56	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
57	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
58	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
59	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
60	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
61	35	http://dev.mysql.com/doc/refman/5.7/en/cast-functions.html
62	2	http://dev.mysql.com/doc/refman/5.7/en/binlog.html
63	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
64	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
65	3	http://dev.mysql.com/doc/refman/5.7/en/bit-functions.html
66	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
67	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
68	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
69	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
70	10	http://dev.mysql.com/doc/refman/5.7/en/blob.html
71	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
72	20	http://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html
73	2	http://dev.mysql.com/doc/refman/5.7/en/cache-index.html
74	9	http://dev.mysql.com/doc/refman/5.7/en/call.html
75	7	http://dev.mysql.com/doc/refman/5.7/en/control-flow-functions.html
76	5	http://dev.mysql.com/doc/refman/5.7/en/case.html
77	35	http://dev.mysql.com/doc/refman/5.7/en/cast-functions.html
78	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
79	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
80	32	http://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html
81	37	http://dev.mysql.com/doc/refman/5.7/en/change-master-to.html
82	37	http://dev.mysql.com/doc/refman/5.7/en/change-replication-filter.html
83	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
84	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
85	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
86	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
87	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
88	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
89	36	http://dev.mysql.com/doc/refman/5.7/en/check-table.html
90	36	http://dev.mysql.com/doc/refman/5.7/en/checksum-table.html
91	5	http://dev.mysql.com/doc/refman/5.7/en/close.html
92	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
93	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
94	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
95	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
96	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
97	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
98	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
99	8	http://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html
100	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
101	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
102	35	http://dev.mysql.com/doc/refman/5.7/en/cast-functions.html
103	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
104	20	http://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html
105	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
106	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
107	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
108	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
109	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
110	8	http://dev.mysql.com/doc/refman/5.7/en/create-database.html
111	8	http://dev.mysql.com/doc/refman/5.7/en/create-event.html
112	8	http://dev.mysql.com/doc/refman/5.7/en/create-function.html
113	38	http://dev.mysql.com/doc/refman/5.7/en/create-function-udf.html
114	8	http://dev.mysql.com/doc/refman/5.7/en/create-index.html
115	8	http://dev.mysql.com/doc/refman/5.7/en/create-logfile-group.html
116	8	http://dev.mysql.com/doc/refman/5.7/en/create-procedure.html
117	8	http://dev.mysql.com/doc/refman/5.7/en/create-server.html
118	8	http://dev.mysql.com/doc/refman/5.7/en/create-table.html
119	8	http://dev.mysql.com/doc/refman/5.7/en/create-tablespace.html
120	8	http://dev.mysql.com/doc/refman/5.7/en/create-trigger.html
121	1	http://dev.mysql.com/doc/refman/5.7/en/create-user.html
122	8	http://dev.mysql.com/doc/refman/5.7/en/create-view.html
123	27	http://dev.mysql.com/doc/refman/5.7/en/enterprise-encryption-functions.html
124	27	http://dev.mysql.com/doc/refman/5.7/en/enterprise-encryption-functions.html
125	27	http://dev.mysql.com/doc/refman/5.7/en/enterprise-encryption-functions.html
126	27	http://dev.mysql.com/doc/refman/5.7/en/enterprise-encryption-functions.html
127	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
128	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
129	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
130	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
131	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
132	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
133	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
134	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
135	10	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-type-overview.html
136	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
137	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
138	10	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-type-overview.html
139	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
140	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
141	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
142	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
143	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
144	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
145	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
146	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
147	37	http://dev.mysql.com/doc/refman/5.7/en/deallocate-prepare.html
148	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
149	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
150	5	http://dev.mysql.com/doc/refman/5.7/en/declare-condition.html
151	5	http://dev.mysql.com/doc/refman/5.7/en/declare-cursor.html
152	5	http://dev.mysql.com/doc/refman/5.7/en/declare-handler.html
153	5	http://dev.mysql.com/doc/refman/5.7/en/declare-local-variable.html
154	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
155	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
156	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
157	9	http://dev.mysql.com/doc/refman/5.7/en/delete.html
158	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
159	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
160	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
161	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
162	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
163	29	http://dev.mysql.com/doc/refman/5.7/en/arithmetic-functions.html
164	9	http://dev.mysql.com/doc/refman/5.7/en/do.html
165	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
166	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
167	8	http://dev.mysql.com/doc/refman/5.7/en/drop-database.html
168	8	http://dev.mysql.com/doc/refman/5.7/en/drop-event.html
169	8	http://dev.mysql.com/doc/refman/5.7/en/drop-function.html
170	38	http://dev.mysql.com/doc/refman/5.7/en/drop-function-udf.html
171	8	http://dev.mysql.com/doc/refman/5.7/en/drop-index.html
172	8	http://dev.mysql.com/doc/refman/5.7/en/drop-procedure.html
173	8	http://dev.mysql.com/doc/refman/5.7/en/drop-server.html
174	8	http://dev.mysql.com/doc/refman/5.7/en/drop-table.html
175	8	http://dev.mysql.com/doc/refman/5.7/en/drop-tablespace.html
176	8	http://dev.mysql.com/doc/refman/5.7/en/drop-trigger.html
177	1	http://dev.mysql.com/doc/refman/5.7/en/drop-user.html
178	8	http://dev.mysql.com/doc/refman/5.7/en/drop-view.html
179	9	http://dev.mysql.com/doc/refman/5.7/en/select.html
180	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
181	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
182	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
183	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
184	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
185	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
186	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
187	37	http://dev.mysql.com/doc/refman/5.7/en/execute.html
188	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
189	39	http://dev.mysql.com/doc/refman/5.7/en/explain.html
190	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
191	32	http://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html
192	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
193	35	http://dev.mysql.com/doc/refman/5.7/en/xml-functions.html
194	5	http://dev.mysql.com/doc/refman/5.7/en/fetch.html
195	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
196	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
197	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
198	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
199	2	http://dev.mysql.com/doc/refman/5.7/en/flush.html
200	2	http://dev.mysql.com/doc/refman/5.7/en/query-cache-status-and-maintenance.html
201	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
202	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
203	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
204	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
205	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
206	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
207	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
208	16	http://dev.mysql.com/doc/refman/5.7/en/creating-spatial-columns.html
209	16	http://dev.mysql.com/doc/refman/5.7/en/gis-geometry-class-hierarchy.html
210	17	http://dev.mysql.com/doc/refman/5.7/en/gis-mysql-specific-functions.html
211	20	http://dev.mysql.com/doc/refman/5.7/en/gis-geometrycollection-property-functions.html
212	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
213	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
214	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
215	5	http://dev.mysql.com/doc/refman/5.7/en/get-diagnostics.html
216	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
217	25	http://dev.mysql.com/doc/refman/5.7/en/locking-functions.html
218	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
219	1	http://dev.mysql.com/doc/refman/5.7/en/grant.html
220	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
221	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
222	27	http://dev.mysql.com/doc/refman/5.7/en/gtid-functions.html
223	27	http://dev.mysql.com/doc/refman/5.7/en/gtid-functions.html
224	9	http://dev.mysql.com/doc/refman/5.7/en/handler.html
225	2	http://dev.mysql.com/doc/refman/5.7/en/mysql-server-side-help.html
226	39	http://dev.mysql.com/doc/refman/5.7/en/help.html
227	21	
228	21	
229	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
230	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
231	7	http://dev.mysql.com/doc/refman/5.7/en/control-flow-functions.html
232	5	http://dev.mysql.com/doc/refman/5.7/en/if.html
233	7	http://dev.mysql.com/doc/refman/5.7/en/control-flow-functions.html
234	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
235	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
236	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
237	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
238	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
239	9	http://dev.mysql.com/doc/refman/5.7/en/insert.html
240	9	http://dev.mysql.com/doc/refman/5.7/en/insert-delayed.html
241	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
242	9	http://dev.mysql.com/doc/refman/5.7/en/insert-select.html
243	30	http://dev.mysql.com/doc/refman/5.7/en/install-plugin.html
244	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
245	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
246	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
247	32	http://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html
248	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
249	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
250	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
251	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
252	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
253	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
254	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
255	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
256	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
257	37	http://dev.mysql.com/doc/refman/5.7/en/set-transaction.html
258	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
259	25	http://dev.mysql.com/doc/refman/5.7/en/locking-functions.html
260	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
261	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
262	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
263	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
264	25	http://dev.mysql.com/doc/refman/5.7/en/locking-functions.html
265	5	http://dev.mysql.com/doc/refman/5.7/en/iterate.html
266	9	http://dev.mysql.com/doc/refman/5.7/en/join.html
267	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
268	27	http://dev.mysql.com/doc/refman/5.7/en/json-creation-functions.html
269	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
270	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
271	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
272	27	http://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html
273	27	http://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html
274	27	http://dev.mysql.com/doc/refman/5.7/en/json-attribute-functions.html
275	27	http://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html
276	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
277	27	http://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html
278	27	http://dev.mysql.com/doc/refman/5.7/en/json-attribute-functions.html
279	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
280	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
281	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
282	27	http://dev.mysql.com/doc/refman/5.7/en/json-creation-functions.html
283	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
284	27	http://dev.mysql.com/doc/refman/5.7/en/json-utility-functions.html
285	27	http://dev.mysql.com/doc/refman/5.7/en/json-creation-functions.html
286	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
287	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
288	27	http://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html
289	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
290	27	http://dev.mysql.com/doc/refman/5.7/en/json-utility-functions.html
291	27	http://dev.mysql.com/doc/refman/5.7/en/json-attribute-functions.html
292	27	http://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html
293	27	http://dev.mysql.com/doc/refman/5.7/en/json-attribute-functions.html
294	2	http://dev.mysql.com/doc/refman/5.7/en/kill.html
295	5	http://dev.mysql.com/doc/refman/5.7/en/statement-labels.html
296	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
297	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
298	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
299	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
300	5	http://dev.mysql.com/doc/refman/5.7/en/leave.html
301	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
302	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
303	35	http://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html
304	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
305	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
306	17	http://dev.mysql.com/doc/refman/5.7/en/gis-mysql-specific-functions.html
307	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
308	9	http://dev.mysql.com/doc/refman/5.7/en/load-data.html
309	2	http://dev.mysql.com/doc/refman/5.7/en/load-index.html
310	9	http://dev.mysql.com/doc/refman/5.7/en/load-xml.html
311	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
312	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
313	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
314	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
315	37	http://dev.mysql.com/doc/refman/5.7/en/lock-tables.html
316	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
317	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
318	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
319	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
320	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
321	5	http://dev.mysql.com/doc/refman/5.7/en/loop.html
322	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
323	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
324	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
325	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
326	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
327	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
328	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
329	35	http://dev.mysql.com/doc/refman/5.7/en/fulltext-search.html
330	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
331	27	http://dev.mysql.com/doc/refman/5.7/en/gis-class-geometry.html
332	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
333	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
334	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
335	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
336	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
337	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
338	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
339	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
340	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
341	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
342	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
343	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
344	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
345	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
346	34	http://dev.mysql.com/doc/refman/5.7/en/merge-storage-engine.html
347	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
348	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
349	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
350	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
351	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
352	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
353	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
354	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
355	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
356	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
357	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
358	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
359	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
360	17	http://dev.mysql.com/doc/refman/5.7/en/gis-mysql-specific-functions.html
361	17	http://dev.mysql.com/doc/refman/5.7/en/gis-mysql-specific-functions.html
362	17	http://dev.mysql.com/doc/refman/5.7/en/gis-mysql-specific-functions.html
363	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
364	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
365	4	http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html
366	35	http://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html
367	35	http://dev.mysql.com/doc/refman/5.7/en/regexp.html
368	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
369	7	http://dev.mysql.com/doc/refman/5.7/en/control-flow-functions.html
370	20	http://dev.mysql.com/doc/refman/5.7/en/gis-geometrycollection-property-functions.html
371	32	http://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html
372	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
373	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
374	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
375	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
376	5	http://dev.mysql.com/doc/refman/5.7/en/open.html
377	36	http://dev.mysql.com/doc/refman/5.7/en/optimize-table.html
378	26	http://dev.mysql.com/doc/refman/5.7/en/logical-operators.html
379	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
380	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
381	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
382	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
383	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
384	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
385	17	http://dev.mysql.com/doc/refman/5.7/en/gis-mysql-specific-functions.html
386	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
387	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
388	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
389	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
390	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
391	17	http://dev.mysql.com/doc/refman/5.7/en/gis-mysql-specific-functions.html
392	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
393	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
394	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
395	37	http://dev.mysql.com/doc/refman/5.7/en/prepare.html
396	33	http://dev.mysql.com/doc/refman/5.7/en/procedure-analyse.html
397	37	http://dev.mysql.com/doc/refman/5.7/en/purge-binary-logs.html
398	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
399	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
400	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
401	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
402	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
403	35	http://dev.mysql.com/doc/refman/5.7/en/regexp.html
404	25	http://dev.mysql.com/doc/refman/5.7/en/locking-functions.html
405	25	http://dev.mysql.com/doc/refman/5.7/en/locking-functions.html
406	8	http://dev.mysql.com/doc/refman/5.7/en/rename-table.html
407	1	http://dev.mysql.com/doc/refman/5.7/en/rename-user.html
408	36	http://dev.mysql.com/doc/refman/5.7/en/repair-table.html
409	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
410	5	http://dev.mysql.com/doc/refman/5.7/en/repeat.html
411	9	http://dev.mysql.com/doc/refman/5.7/en/replace.html
412	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
413	2	http://dev.mysql.com/doc/refman/5.7/en/reset.html
414	37	http://dev.mysql.com/doc/refman/5.7/en/reset-master.html
415	37	http://dev.mysql.com/doc/refman/5.7/en/reset-slave.html
416	5	http://dev.mysql.com/doc/refman/5.7/en/resignal.html
417	5	http://dev.mysql.com/doc/refman/5.7/en/return.html
418	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
419	1	http://dev.mysql.com/doc/refman/5.7/en/revoke.html
420	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
421	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
422	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
423	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
424	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
425	37	http://dev.mysql.com/doc/refman/5.7/en/savepoint.html
426	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
427	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
428	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
429	9	http://dev.mysql.com/doc/refman/5.7/en/select.html
430	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
431	2	http://dev.mysql.com/doc/refman/5.7/en/set-variable.html
432	2	http://dev.mysql.com/doc/refman/5.7/en/set-character-set.html
433	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
434	37	http://dev.mysql.com/doc/refman/5.7/en/set-global-sql-slave-skip-counter.html
435	2	http://dev.mysql.com/doc/refman/5.7/en/set-names.html
436	1	http://dev.mysql.com/doc/refman/5.7/en/set-password.html
437	37	http://dev.mysql.com/doc/refman/5.7/en/set-sql-log-bin.html
438	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
439	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
440	2	http://dev.mysql.com/doc/refman/5.7/en/show.html
441	2	http://dev.mysql.com/doc/refman/5.7/en/show-binary-logs.html
442	2	http://dev.mysql.com/doc/refman/5.7/en/show-binlog-events.html
443	2	http://dev.mysql.com/doc/refman/5.7/en/show-character-set.html
444	2	http://dev.mysql.com/doc/refman/5.7/en/show-collation.html
445	2	http://dev.mysql.com/doc/refman/5.7/en/show-columns.html
446	2	http://dev.mysql.com/doc/refman/5.7/en/show-create-database.html
447	2	http://dev.mysql.com/doc/refman/5.7/en/show-create-event.html
448	2	http://dev.mysql.com/doc/refman/5.7/en/show-create-function.html
449	2	http://dev.mysql.com/doc/refman/5.7/en/show-create-procedure.html
450	2	http://dev.mysql.com/doc/refman/5.7/en/show-create-table.html
451	2	http://dev.mysql.com/doc/refman/5.7/en/show-create-trigger.html
452	2	http://dev.mysql.com/doc/refman/5.7/en/show-create-user.html
453	2	http://dev.mysql.com/doc/refman/5.7/en/show-create-view.html
454	2	http://dev.mysql.com/doc/refman/5.7/en/show-databases.html
455	2	http://dev.mysql.com/doc/refman/5.7/en/show-engine.html
456	2	http://dev.mysql.com/doc/refman/5.7/en/show-engines.html
457	2	http://dev.mysql.com/doc/refman/5.7/en/show-errors.html
458	2	http://dev.mysql.com/doc/refman/5.7/en/show-events.html
459	2	http://dev.mysql.com/doc/refman/5.7/en/show-function-code.html
460	2	http://dev.mysql.com/doc/refman/5.7/en/show-function-status.html
461	2	http://dev.mysql.com/doc/refman/5.7/en/show-grants.html
462	2	http://dev.mysql.com/doc/refman/5.7/en/show-index.html
463	2	http://dev.mysql.com/doc/refman/5.7/en/show-master-status.html
464	2	http://dev.mysql.com/doc/refman/5.7/en/show-open-tables.html
465	2	http://dev.mysql.com/doc/refman/5.7/en/show-plugins.html
466	2	http://dev.mysql.com/doc/refman/5.7/en/show-privileges.html
467	2	http://dev.mysql.com/doc/refman/5.7/en/show-procedure-code.html
468	2	http://dev.mysql.com/doc/refman/5.7/en/show-procedure-status.html
469	2	http://dev.mysql.com/doc/refman/5.7/en/show-processlist.html
470	2	http://dev.mysql.com/doc/refman/5.7/en/show-profile.html
471	2	http://dev.mysql.com/doc/refman/5.7/en/show-profiles.html
472	2	http://dev.mysql.com/doc/refman/5.7/en/show-relaylog-events.html
473	2	http://dev.mysql.com/doc/refman/5.7/en/show-slave-hosts.html
474	2	http://dev.mysql.com/doc/refman/5.7/en/show-slave-status.html
475	2	http://dev.mysql.com/doc/refman/5.7/en/show-status.html
476	2	http://dev.mysql.com/doc/refman/5.7/en/show-table-status.html
477	2	http://dev.mysql.com/doc/refman/5.7/en/show-tables.html
478	2	http://dev.mysql.com/doc/refman/5.7/en/show-triggers.html
479	2	http://dev.mysql.com/doc/refman/5.7/en/show-variables.html
480	2	http://dev.mysql.com/doc/refman/5.7/en/show-warnings.html
481	2	http://dev.mysql.com/doc/refman/5.7/en/shutdown.html
482	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
483	5	http://dev.mysql.com/doc/refman/5.7/en/signal.html
484	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
485	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
486	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
487	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
488	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
489	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
490	16	http://dev.mysql.com/doc/refman/5.7/en/creating-spatial-indexes.html
491	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
492	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
493	37	http://dev.mysql.com/doc/refman/5.7/en/start-slave.html
494	37	http://dev.mysql.com/doc/refman/5.7/en/commit.html
495	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
496	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
497	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
498	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
499	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
500	37	http://dev.mysql.com/doc/refman/5.7/en/stop-slave.html
501	35	http://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html
502	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
503	32	http://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html
504	40	http://dev.mysql.com/doc/refman/5.7/en/gis-format-conversion-functions.html
505	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-geojson-functions.html
506	40	http://dev.mysql.com/doc/refman/5.7/en/gis-format-conversion-functions.html
507	20	http://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html
508	20	http://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html
509	32	http://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html
510	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
511	20	http://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html
512	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
513	20	http://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html
514	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
515	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
516	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
517	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-convenience-functions.html
518	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
519	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
520	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
521	32	http://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html
522	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-geohash-functions.html
523	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
524	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
525	20	http://dev.mysql.com/doc/refman/5.7/en/gis-geometrycollection-property-functions.html
526	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
527	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-geojson-functions.html
528	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
529	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
530	32	http://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html
531	20	http://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html
532	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
533	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
534	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
535	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
536	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-convenience-functions.html
537	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-geohash-functions.html
538	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
539	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
540	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
541	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-geohash-functions.html
542	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-convenience-functions.html
543	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
544	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
545	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
546	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
547	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
548	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
549	20	http://dev.mysql.com/doc/refman/5.7/en/gis-geometrycollection-property-functions.html
550	32	http://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html
551	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
552	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
553	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-geohash-functions.html
554	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
555	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
556	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
557	41	http://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html
558	40	http://dev.mysql.com/doc/refman/5.7/en/gis-wkb-functions.html
559	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-convenience-functions.html
560	18	http://dev.mysql.com/doc/refman/5.7/en/gis-general-property-functions.html
561	24	http://dev.mysql.com/doc/refman/5.7/en/gis-linestring-property-functions.html
562	20	http://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html
563	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
564	20	http://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html
565	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-convenience-functions.html
566	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
567	31	http://dev.mysql.com/doc/refman/5.7/en/gis-point-property-functions.html
568	31	http://dev.mysql.com/doc/refman/5.7/en/gis-point-property-functions.html
569	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
570	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
571	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
572	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
573	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
574	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
575	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
576	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
577	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
578	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
579	10	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-type-overview.html
580	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
581	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
582	10	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-type-overview.html
583	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
584	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
585	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
586	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
587	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
588	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
589	10	http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
590	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
591	19	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html
592	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
593	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
594	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
595	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
596	23	http://dev.mysql.com/doc/refman/5.7/en/boolean-literals.html
597	29	http://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html
598	8	http://dev.mysql.com/doc/refman/5.7/en/truncate-table.html
599	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
600	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
601	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
602	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
603	30	http://dev.mysql.com/doc/refman/5.7/en/uninstall-plugin.html
604	9	http://dev.mysql.com/doc/refman/5.7/en/union.html
605	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
606	9	http://dev.mysql.com/doc/refman/5.7/en/update.html
607	35	http://dev.mysql.com/doc/refman/5.7/en/xml-functions.html
608	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
609	39	http://dev.mysql.com/doc/refman/5.7/en/use.html
610	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
611	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
612	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
613	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
614	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
615	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
616	12	http://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html
617	28	http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
618	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
619	10	http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
620	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
621	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
622	14	http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html
623	22	http://dev.mysql.com/doc/refman/5.7/en/information-functions.html
624	27	http://dev.mysql.com/doc/refman/5.7/en/gtid-functions.html
625	27	http://dev.mysql.com/doc/refman/5.7/en/gtid-functions.html
626	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
627	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
628	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
629	35	http://dev.mysql.com/doc/refman/5.7/en/string-functions.html
630	5	http://dev.mysql.com/doc/refman/5.7/en/while.html
631	27	http://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html
632	41	http://dev.mysql.com/doc/refman/5.7/en/gis-data-formats.html
633	31	http://dev.mysql.com/doc/refman/5.7/en/gis-point-property-functions.html
634	37	http://dev.mysql.com/doc/refman/5.7/en/xa-statements.html
635	26	http://dev.mysql.com/doc/refman/5.7/en/logical-operators.html
636	31	http://dev.mysql.com/doc/refman/5.7/en/gis-point-property-functions.html
637	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
638	10	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-type-overview.html
639	11	http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html
640	3	http://dev.mysql.com/doc/refman/5.7/en/bit-functions.html
641	3	http://dev.mysql.com/doc/refman/5.7/en/bit-functions.html
642	3	http://dev.mysql.com/doc/refman/5.7/en/bit-functions.html